version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - bike_rental:/var/lib/db
    environment:
      MYSQL_DATABASE: bike_rental
      MYSQL_ROOT_PASSWORD: fishy
    ports:
      - 3306:3306
    
volumes:
  bike_rental:
